spring.application.name=claimstreams
# Enable Java 21 Virtual Threads (Project Loom)
spring.threads.virtual.enabled=true
# Database Properties
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:claimstream}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgrespassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Redis Properties
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Kafka Properties
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=claimstream-adjudication-group
spring.kafka.consumer.auto-offset-reset=earliest