spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASS_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: ${REDIS_PORT_DEV}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS_DEV}
    consumer:
      group-id: claimstream-adjudication-group
      auto-offset-reset: earliest